version: "3.6"

services:
  spark-master:
    image: spark-master
    container_name: spark-master
    restart: always
    cpus: ".4"
    mem_limit: "10g"
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
      - /Users/zsu/Projects/DE/encore/spark_nlp/scripts:/opt/workspace/scripts
    networks:
      - sparknet

  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    restart: always
    cpus: ".2"
    mem_limit: "5g"
    environment:
      SPARK_WORKER_CORES: "1"
      SPARK_WORKER_MEMORY: "4096m"
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
      - /Users/zsu/Projects/DE/encore/spark_nlp/scripts:/opt/workspace/scripts
    networks:
      - sparknet
    depends_on:
      - spark-master

  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    restart: always
    cpus: ".2"
    mem_limit: "5g"
    environment:
      SPARK_WORKER_CORES: "1"
      SPARK_WORKER_MEMORY: "4096m"
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
      - /Users/zsu/Projects/DE/encore/spark_nlp/scripts:/opt/workspace/scripts
    networks:
      - sparknet
    depends_on:
      - spark-master

# volumes
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  mongodb2:
  mongodb_config2:

# networks
networks:
  sparknet:
    external:
      name: airflownet
